import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { fetchFilterOptions, fetchGridData } from '../api/forecastApi';
import './Dashboard/Dashboard.css';
import './Summary.css';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const round = v => Number.isFinite(Number(v)) ? Math.round(Number(v)) : 0;
const fmt = v => round(v).toLocaleString('en-US');
const pct = (a,b) => b ? `${Math.round((a/b)*100).toLocaleString('en-US')}%` : '—';
const sum = a => (a || []).reduce((s,v) => s + (Number(v)||0), 0);
const addArrays = (items, key, len=12) => Array.from({length:len},(_,i)=>items.reduce((s,x)=>s+(Number((x[key]||[])[i])||0),0));

function Filter({label,value,options,onChange,required}) {
  return <label className="filter-field"><span>{label}{required && <b> *</b>}</span><select value={value} onChange={e=>onChange(e.target.value)}>{['All',...(options||[]).filter(x=>x!=='All')].map(x=><option key={x} value={x}>{x}</option>)}</select></label>;
}

export default function Summary(){
  const [filters,setFilters]=useState({state:'All',chainStatus:'All',premiseType:'All',topChain:'All',dateVersion:'',brandType:'All'});
  const [opts,setOpts]=useState({states:[],chainStatuses:[],premiseTypes:[],topChains:[],brands:[],versions:[]});
  const [items,setItems]=useState([]); const [stats,setStats]=useState({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [varianceMode,setVarianceMode]=useState('budget'); const [yearFilter,setYearFilter]=useState('All Years'); const [combo,setCombo]=useState('All Combinations'); const [search,setSearch]=useState('');

  useEffect(()=>{(async()=>{try{const d=await fetchFilterOptions(); const versions=d.date_versions||[]; setOpts({states:d.states||[],chainStatuses:d.chain_statuses||[],premiseTypes:d.premise_types||[],topChains:d.top_chains||[],brands:d.brands||[],versions}); setFilters(f=>({...f,dateVersion:d.default_date_version||versions[0]||''}));}catch(e){setError(e.message)}finally{setLoading(false)}})()},[]);
  useEffect(()=>{if(!filters.dateVersion)return;(async()=>{try{const d=await fetchFilterOptions({state:filters.state,chainStatus:filters.chainStatus,premiseType:filters.premiseType,brandType:filters.brandType,dateVersion:filters.dateVersion});setOpts(o=>({...o,premiseTypes:d.premise_types||o.premiseTypes,topChains:d.top_chains||[],brands:d.brands||o.brands,states:d.states||o.states,chainStatuses:d.chain_statuses||o.chainStatuses,versions:d.date_versions||o.versions}))}catch{}})()},[filters.state,filters.chainStatus,filters.premiseType,filters.brandType,filters.dateVersion]);
  const load=useCallback(async()=>{if(!filters.dateVersion)return;setLoading(true);setError('');try{const d=await fetchGridData(filters);setItems(d.grid_data||[]);setStats(d.statistics||{})}catch(e){setError(e.response?.data?.detail||e.message)}finally{setLoading(false)}},[filters]);
  useEffect(()=>{load()},[load]);
  const selectedYear=Number((filters.dateVersion||'').slice(0,4))||new Date().getFullYear(); const prev1=selectedYear-2, prev2=selectedYear-1;
  const totals=useMemo(()=>{const actual=sum(items.flatMap(x=>x.actuals2026||[])), forecast=sum(items.flatMap(x=>x.forecasts2026||[])), budget=sum(items.flatMap(x=>x[`budget${selectedYear}`]||[]));return{actual,forecast,consensus:actual+forecast,budget,vbud:actual+forecast-budget}},[items,selectedYear]);
  const rows=useMemo(()=>items.filter(x=>x.planning_id.toLowerCase().includes(search.toLowerCase())).map(x=>{const a=sum(x.actuals2026),f=sum(x.forecasts2026),b=sum(x[`budget${selectedYear}`]);const prior=sum(x[`actuals${selectedYear-1}`]); const reference=varianceMode==='budget'?b:prior; return{id:x.planning_id,a,f,c:a+f,b,v:a+f-reference,p:reference?(a+f-reference)/reference*100:null}}),[items,search,selectedYear,varianceMode]);
  const matrix=useMemo(()=>{const a1=addArrays(items,'actuals2024'),a2=addArrays(items,'actuals2025');const act=addArrays(items,'actuals2026'),fcRaw=items.map(x=>x.forecasts2026||[]);const actualCount=act.filter((_,i)=>items.some(x=>(x.actuals2026||[])[i]!==undefined)).length;const fc=Array(12).fill(0);fcRaw.forEach(arr=>arr.forEach((v,i)=>{const idx=actualCount+i;if(idx<12)fc[idx]+=Number(v)||0}));const consensus=act.map((v,i)=>v+fc[i]);const stat=addArrays(items,'prevForecasts2026'),budget=addArrays(items,`budget${selectedYear}`);return[{label:String(prev1),type:'actual',vals:a1},{label:String(prev2),type:'actual',vals:a2},{label:`Consensus (${selectedYear})`,type:'consensus',vals:consensus,actualCount},{label:`Statistical Forecast (${selectedYear})`,type:'stat',vals:stat},{label:`Budget (${selectedYear})`,type:'budget',vals:budget},{label:`${varianceMode==='budget'?'vBUD':'vPY'} (${selectedYear})`,type:'variance',vals:consensus.map((v,i)=>v-(varianceMode==='budget'?budget[i]:a2[i]))},{label:`${varianceMode==='budget'?'vBUD':'vPY'} % (${selectedYear})`,type:'percent',vals:consensus.map((v,i)=>{const base=varianceMode==='budget'?budget[i]:a2[i];return base?((v-base)/base)*100:null})}]},[items,selectedYear,prev1,prev2,varianceMode]);
  const visibleMatrix=matrix.filter(r=>{if(yearFilter!== 'All Years' && !r.label.includes(yearFilter))return false;if(combo==='Actuals + Forecasts')return ['actual','consensus'].includes(r.type);if(combo==='Statistical Forecasts Only')return r.type==='stat';if(combo==='Budget Only')return r.type==='budget';if(combo==='Variance to Budget' || combo==='Variance to Prior Year')return ['variance','percent'].includes(r.type);return true});
  const selectedVarianceBase=varianceMode==='budget'?totals.budget:sum(items.flatMap(x=>x[`actuals${selectedYear-1}`]||[])); const selectedVariance=totals.consensus-selectedVarianceBase; const varianceLabel=varianceMode==='budget'?'vBUD':'vPY';
  const clear=()=>setFilters(f=>({state:'All',chainStatus:'All',premiseType:'All',topChain:'All',dateVersion:opts.versions[0]||f.dateVersion,brandType:'All'}));
  return <div className="dashboard-page summary-page">
    {loading && <div className="page-loading-overlay" role="status" aria-live="polite"><div className="page-loading-content"><div className="page-loading-spinner"/><strong>Loading Summary...</strong><span>Fetching your filtered forecast data.</span></div></div>}<section className="dashboard-header"><div><p className="eyebrow">COMMERCIAL PLANNING</p><h1>Forecast Summary</h1><p>Consolidated view across all Planning IDs matching the selected filters.</p></div></section>
    <section className="filters-card"><div className="filters-title-row"><h2>Filters</h2><div><span className="sync-text">Synced to Database</span><button className="clear-filters-btn" onClick={clear}>Clear Filters</button></div></div><div className="filters-grid">
      <Filter label="State" value={filters.state} options={opts.states} onChange={v=>setFilters(f=>({...f,state:v}))}/><Filter label="Chain Status" value={filters.chainStatus} options={opts.chainStatuses} onChange={v=>setFilters(f=>({...f,chainStatus:v}))}/><Filter label="Premise Type" value={filters.premiseType} options={opts.premiseTypes} onChange={v=>setFilters(f=>({...f,premiseType:v}))}/><Filter label="Top Chain" value={filters.topChain} options={opts.topChains} onChange={v=>setFilters(f=>({...f,topChain:v}))}/><Filter label="Date Version" required value={filters.dateVersion} options={opts.versions} onChange={v=>setFilters(f=>({...f,dateVersion:v}))}/><Filter label="Brand Type (optional)" value={filters.brandType} options={opts.brands} onChange={v=>setFilters(f=>({...f,brandType:v}))}/>
    </div></section>
    {error&&<div className="summary-error">{error}</div>}{loading&&<div className="summary-loading">Loading summary from database…</div>}
    <section className="summary-kpis"><div><span>Actuals {selectedYear}</span><strong>{fmt(totals.actual)} <small>9L</small></strong></div><div><span>Forecast {selectedYear}</span><strong>{fmt(totals.forecast)} <small>9L</small></strong></div><div className="primary"><span>{selectedYear} Total</span><strong>{fmt(totals.consensus)} <small>9L</small></strong></div><div><span>Annual Target</span><strong>{fmt(totals.budget)} <small>9L</small></strong><em>{varianceLabel} {fmt(selectedVariance)} · {pct(selectedVariance,selectedVarianceBase)}</em></div></section>
    <section className="summary-card"><div className="summary-card-head"><div><p className="eyebrow">PLANNING ID SUMMARY</p><h2>{filters.state==='All'?'All States':filters.state} · {items.length} Planning IDs</h2></div><input className="summary-search" placeholder="Search Planning ID" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="summary-table-wrap"><table className="summary-table"><thead><tr><th>Planning ID</th><th>Actuals {selectedYear}</th><th>Forecast {selectedYear}</th><th>Consensus {selectedYear}</th><th>Budget {selectedYear}</th><th>{varianceLabel}</th><th>{varianceLabel} %</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{fmt(r.a)}</td><td>{fmt(r.f)}</td><td>{fmt(r.c)}</td><td>{fmt(r.b)}</td><td className={r.v<0?'negative':'positive'}>{fmt(r.v)}</td><td className={(r.p||0)<0?'negative':'positive'}>{r.p==null?'—':`${Math.round(r.p)}%`}</td></tr>)}</tbody><tfoot><tr><th>TOTAL</th><th>{fmt(totals.actual)}</th><th>{fmt(totals.forecast)}</th><th>{fmt(totals.consensus)}</th><th>{fmt(totals.budget)}</th><th>{fmt(selectedVariance)}</th><th>{pct(selectedVariance,selectedVarianceBase)}</th></tr></tfoot></table></div></section>
    <div className="variance-toggle" role="group" aria-label="Variance comparison"><span>Variance comparison</span><button type="button" className={varianceMode==='budget'?'selected':''} aria-pressed={varianceMode==='budget'} onClick={()=>setVarianceMode('budget')}>Current Year Variance</button><button type="button" className={varianceMode==='prior'?'selected':''} aria-pressed={varianceMode==='prior'} onClick={()=>setVarianceMode('prior')}>Prior Year Variance</button></div>
    <section className="summary-card"><div className="matrix-head"><div><p className="eyebrow">FORECAST MATRIX</p><h2>Aggregated Monthly Forecast</h2></div><div className="matrix-controls"><label>YEAR FILTER<select value={yearFilter} onChange={e=>setYearFilter(e.target.value)}><option>All Years</option><option>{prev1}</option><option>{prev2}</option><option>{selectedYear}</option></select></label><label>VIEW COMBINATION FILTER<select value={combo} onChange={e=>setCombo(e.target.value)}><option>All Combinations</option><option>Actuals + Forecasts</option><option>Statistical Forecasts Only</option><option>Budget Only</option><option>Variance to Budget</option><option>Variance to Prior Year</option></select></label></div></div><div className="summary-table-wrap"><table className="matrix-table"><thead><tr><th>YEAR / TYPE</th>{MONTHS.map(m=><th key={m}>{m}</th>)}<th>TOTAL</th></tr></thead><tbody>{visibleMatrix.map(r=><tr key={r.label} className={`matrix-${r.type}`}><th>{r.label}</th>{r.vals.map((v,i)=><td key={i}>{r.type==='percent'?(v==null?'—':`${Math.round(v)}%`):fmt(v)}{r.type==='consensus'&&<small>{i<(r.actualCount||0)?'Actuals':'Forecast'}</small>}</td>)}<td><b>{r.type==='percent' ? pct(selectedVariance,selectedVarianceBase) : r.type==='variance' ? fmt(selectedVariance) : fmt(sum(r.vals))}</b></td></tr>)}</tbody></table></div></section>
    <div className="summary-foot">Loaded {stats.latest_load_timestamp||'—'} · Date Version {filters.dateVersion||'—'}</div>
  </div>
}
